/* Generated By:JavaCC: Do not edit this line. ABCParserConstants.java */
public interface ABCParserConstants {

  int EOF = 0;
  int SKIP_WHITESPACE = 1;
  int COMMENT = 2;
  int DIGIT = 3;
  int LETTER = 4;
  int UPPER_LETTER = 5;
  int LOWER_LETTER = 6;
  int NOTE1 = 7;
  int NOTE2 = 8;
  int NOTE_UNIT = 9;
  int SHARP_OR_FLAT = 10;
  int SPACE_OR_TAB = 11;
  int EOL = 12;
  int NUMBER = 13;
  int AREA_START = 14;
  int BOOK_START = 15;
  int COMPOSER_START = 16;
  int DISCOGRAPHY_START = 17;
  int FILE_NAME_START = 18;
  int GROUP_START = 19;
  int HISTORY_START = 20;
  int INFO_START = 21;
  int INDEX_START = 22;
  int KEY_START = 23;
  int NOTE_LENGTH_START = 24;
  int METER_START = 25;
  int NOTES_START = 26;
  int ORIGIN_START = 27;
  int PARTS_START = 28;
  int RHYTHM_START = 29;
  int SOURCE_START = 30;
  int TEMPO_START = 31;
  int TITLE_START = 32;
  int WORDS_START = 33;
  int TRANS_NOTE_START = 34;
  int NOTE = 35;
  int NOTE_R = 36;
  int REST = 37;
  int CUSTOM_NOTATION = 38;
  int ACCIDENTAL = 39;
  int OCTAVE_DOWN = 40;
  int OCTAVE_UP = 41;
  int ACCENT_STACCATO = 42;
  int ACCENT_ROLL = 43;
  int ACCENT_UPBOW = 44;
  int ACCENT_DOWNBOW = 45;
  int GRACE_START = 46;
  int GRACE_END = 47;
  int NOTE_CHORD_START = 48;
  int NOTE_CHORD_END = 49;
  int SLUR_START = 50;
  int SLUR_END = 51;
  int BROKEN_RHYTHM_LEFT = 52;
  int BROKEN_RHYTHM_RIGHT = 53;
  int TUPLET_P = 54;
  int TUPLET_Q_OR_R = 55;
  int TUPLET_DIGIT = 56;
  int DIVIDE = 57;
  int TIE = 58;
  int BAR = 59;
  int BAR_DOUBLE = 60;
  int BAR_DOUBLE_START = 61;
  int BAR_DOUBLE_END = 62;
  int BAR_REPEAT_START = 63;
  int BAR_REPEAT_END = 64;
  int BAR_REPEAT_DOUBLE = 65;
  int ACCOMP_CHORD_START = 66;
  int REPEAT = 67;
  int CONTINUATION = 68;
  int JUSTIFICATION = 69;
  int WHITESPACE = 70;
  int TEXT_LINE = 71;
  int INDEX_NUMBER = 72;
  int KEY_NOTE = 73;
  int KEY_BAGPIPE = 74;
  int KEY_GLOBAL_ACCIDENTAL = 75;
  int KEY_EOL = 76;
  int KEY_MODE = 77;
  int MAJOR = 78;
  int MINOR = 79;
  int LYDIAN = 80;
  int IONIAN = 81;
  int MIXOLYDIAN = 82;
  int DORIAN = 83;
  int AEOLIAN = 84;
  int PHRYGIAN = 85;
  int LOCRIAN = 86;
  int ACCOMP_CHORD_NAME = 87;
  int ACCOMP_CHORD_END = 88;
  int METER_COMMON = 89;
  int METER_CUT = 90;
  int METER_FRACTION = 91;
  int METER_TOP = 92;
  int METER_BOTTOM = 93;
  int PART_LABEL = 94;
  int PART_EOL = 95;
  int NOTE_LENGTH_NOTE_UNIT = 96;
  int TEMPO_NOTE_UNIT = 97;
  int TEMPO_ASSIGN = 98;
  int TEMPO_COUNT = 99;

  int IN_ACCOMP_CHORD = 0;
  int IN_INDEX = 1;
  int IN_METER = 2;
  int IN_NOTE_LENGTH = 3;
  int IN_PARTS = 4;
  int IN_TEMPO = 5;
  int IN_TEXT_LINE = 6;
  int IN_KEY = 7;
  int DEFAULT = 8;

  String[] tokenImage = {
    "<EOF>",
    "<SKIP_WHITESPACE>",
    "<COMMENT>",
    "<DIGIT>",
    "<LETTER>",
    "<UPPER_LETTER>",
    "<LOWER_LETTER>",
    "<NOTE1>",
    "<NOTE2>",
    "<NOTE_UNIT>",
    "<SHARP_OR_FLAT>",
    "<SPACE_OR_TAB>",
    "<EOL>",
    "<NUMBER>",
    "\"A:\"",
    "\"B:\"",
    "\"C:\"",
    "\"D:\"",
    "\"F:\"",
    "\"G:\"",
    "\"H:\"",
    "\"I:\"",
    "\"X:\"",
    "\"K:\"",
    "\"L:\"",
    "\"M:\"",
    "\"N:\"",
    "\"O:\"",
    "\"P:\"",
    "\"R:\"",
    "\"S:\"",
    "\"Q:\"",
    "\"T:\"",
    "\"W:\"",
    "\"Z:\"",
    "<NOTE>",
    "<NOTE_R>",
    "\"z\"",
    "<CUSTOM_NOTATION>",
    "<ACCIDENTAL>",
    "<OCTAVE_DOWN>",
    "<OCTAVE_UP>",
    "\".\"",
    "\"~\"",
    "\"u\"",
    "\"v\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<BROKEN_RHYTHM_LEFT>",
    "<BROKEN_RHYTHM_RIGHT>",
    "<TUPLET_P>",
    "<TUPLET_Q_OR_R>",
    "<TUPLET_DIGIT>",
    "\"/\"",
    "\"-\"",
    "\"|\"",
    "\"||\"",
    "\"[|\"",
    "\"|]\"",
    "\"|:\"",
    "\":|\"",
    "\"::\"",
    "\"\\\"\"",
    "<REPEAT>",
    "<CONTINUATION>",
    "<JUSTIFICATION>",
    "<WHITESPACE>",
    "<TEXT_LINE>",
    "<INDEX_NUMBER>",
    "<KEY_NOTE>",
    "<KEY_BAGPIPE>",
    "<KEY_GLOBAL_ACCIDENTAL>",
    "<KEY_EOL>",
    "<KEY_MODE>",
    "<MAJOR>",
    "<MINOR>",
    "<LYDIAN>",
    "<IONIAN>",
    "<MIXOLYDIAN>",
    "<DORIAN>",
    "<AEOLIAN>",
    "<PHRYGIAN>",
    "<LOCRIAN>",
    "<ACCOMP_CHORD_NAME>",
    "\"\\\"\"",
    "\"C\"",
    "\"C|\"",
    "<METER_FRACTION>",
    "<METER_TOP>",
    "<METER_BOTTOM>",
    "<PART_LABEL>",
    "<PART_EOL>",
    "<NOTE_LENGTH_NOTE_UNIT>",
    "<TEMPO_NOTE_UNIT>",
    "\"=\"",
    "<TEMPO_COUNT>",
  };

}
